name: linux

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.36'
          - '5.38'
          - '5.40'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: cpanfile
          sudo: false
          args: --quiet
      - name: Run Tests
        run: prove -lr t
